# Generated by Django 5.2.7 on 2025-10-21 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give your flan a delicious name', max_length=200)),
                ('description', models.TextField(help_text='Describe how amazing your flan is')),
                ('image_url', models.URLField(blank=True, help_text='Paste a flan image URL from Unsplash', max_length=500)),
                ('flan_type', models.CharField(choices=[('vanilla', 'Vanilla Classic'), ('chocolate', 'Chocolate Dream'), ('coconut', 'Coconut Paradise'), ('coffee', 'Coffee Delight'), ('special', "Chef's Special")], default='vanilla', max_length=20)),
                ('is_premium', models.BooleanField(default=False, help_text='Check if this is premium content')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price for premium flans', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
