# Generated by Django 5.2.7 on 2025-10-21 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('receive_weekly_digest', models.BooleanField(default=True)),
                ('receive_new_flan_alerts', models.BooleanField(default=True)),
                ('favorite_flan_type', models.CharField(blank=True, choices=[('vanilla', 'Vanilla Classic'), ('chocolate', 'Chocolate Dream'), ('coconut', 'Coconut Paradise'), ('coffee', 'Coffee Delight'), ('special', "Chef's Special")], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flans.subscriber')),
            ],
        ),
    ]
