# Generated by Django 5.2.7 on 2025-10-23 01:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flans', '0003_alter_emaillog_options_alter_flan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlanCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Creator's display name", max_length=100)),
                ('creator_type', models.CharField(choices=[('grandma', 'Sweet Grandma'), ('chef', 'Professional Chef'), ('influencer', 'Flan Influencer'), ('amateur', 'Home Baker')], default='amateur', max_length=20)),
                ('bio', models.TextField(help_text='Hilarious creator biography')),
                ('profile_image', models.URLField(blank=True, help_text='Creator profile image URL', max_length=500)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('total_flans', models.IntegerField(default=0, help_text='Total flans created (fake stat)')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Total earnings (fake stat)', max_digits=10)),
                ('satisfaction_rate', models.IntegerField(default=95, help_text='Satisfaction percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('instagram_followers', models.CharField(default='10K', help_text='Fake follower count', max_length=50)),
            ],
            options={
                'verbose_name': 'Flan Creator',
                'verbose_name_plural': 'Flan Creators',
                'ordering': ['-is_featured', '-total_earnings'],
            },
        ),
        migrations.AddField(
            model_name='flan',
            name='featured_creator',
            field=models.ForeignKey(blank=True, help_text='Featured creator for this flan (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flans.flancreator'),
        ),
    ]
