# Generated by Django 5.2.7 on 2026-05-06 01:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flans', '0004_flancreator_flan_featured_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flancreator',
            name='total_flans',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='flans.subscriber'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='was_successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flan',
            name='featured_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flans', to='flans.flancreator'),
        ),
        migrations.AlterField(
            model_name='flan',
            name='flan_type',
            field=models.CharField(choices=[('vanilla', 'Vanilla Classic'), ('chocolate', 'Chocolate Dream'), ('coconut', 'Coconut Paradise'), ('coffee', 'Coffee Delight'), ('special', "Chef's Special")], default='vanilla', max_length=20),
        ),
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='flan',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flan',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='flancreator',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flancreator',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='flancreator',
            name='satisfaction_rate',
            field=models.IntegerField(default=95, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='favorite_flan_type',
            field=models.CharField(blank=True, choices=[('vanilla', 'Vanilla Classic'), ('chocolate', 'Chocolate Dream'), ('coconut', 'Coconut Paradise'), ('coffee', 'Coffee Delight'), ('special', "Chef's Special")], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='receive_new_flan_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='receive_weekly_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FlanRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Rating from 1 to 5 flans 🍮', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='flans.flan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flan Rating',
                'verbose_name_plural': 'Flan Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flan', 'score'], name='flans_flanr_flan_id_196552_idx')],
                'unique_together': {('flan', 'user')},
            },
        ),
    ]
